"buy":
  prefixes:
    - buy
    - e
    - shop
    - thrifty
  suffixes:
    - bazaar
    - bodega
    - boutique
    - buy
    - depot
    - exchange
    - hub
    - mart
    - shop
    - shoppe
    - store
    - warehouse
"communicate with":
  prefixes:
    - contact
    - inform
    - share
  suffixes:
    - base
    - cast
    - caster
    - connect
    - connext
    - contact
    - inform
    - informant
    - informer
    - publisher
    - sharer
"create":
  prefixes:
    - forge
    - invent
    - make
  suffixes:
    - artist
    - constructor
    - creator
    - fabricate
    - factory
    - farm
    - forge
    - foundry
    - inception
    - inventor
    - kiln
    - lab
    - machine
    - maker
    - mint
    - origin
    - shop
    - smith
    - source
    - studio
    - works
    - workshop
    - yard
  patterns:
    - "%{keyword}ception"
    - "%{keyword}ventor"
"find":
  prefixes:
    - eureka!
    - search
  suffixes:
    - beacon
    - detective
    - digger
    - eureka
    - finder
    - focus
    - holmes
    - oracle
    - searcher
    - scry
    - sherlock
    - trove
  patterns:
    - "%{keyword}chimedes"
"listen to":
  prefixes:
    - audio
    - ear
    - radio
  suffixes:
    - audio
    - ear
    - phone
    - radio
    - stereo
    - tune
"organize":
  suffixes:
    - book
    - box
    - file
    - folder
    - journal
"pay":
  suffixes:
    - bank
    - banker
    - cash
    - check
    - wallet
"read":
"share":
"store":
  prefixes:
  suffixes:
    - box
    - file
    - folder
"watch":
